### ISSUE TITLE
make the depth-first search

### ISSUE THREAD

**Issue by cvkittler** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#4] opened 2021-02-05 22:28 UTC
**Write a depth-first search algorithm** and test it on a very simple map with nodes and edges that you create yourselves.

Submit:
The A* algorithm IntelliJ project along with your simple map. You do not need to submit the depth-first search pathfinding program.

- [ ] Write the Depth First Search algorithm 
- [ ] Test DFS on the Simple Map

**Comment by Kohmei358** [comment] 2021-02-07 04:26
Duplicate of #9

**Comment by Kohmei358** [comment] 2021-02-07 08:04
Sorry didn't mean to close this

**Closed** 2021-02-11 19:13 UTC
Labels: algo
