### ISSUE TITLE
Prototype Application

### ISSUE THREAD

**Issue by beast-nev** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#46] opened 2021-02-11 18:50 UTC
- [ ] Write a JavaFX program that demonstrates reading your CSV files from Project B and creating an embedded database table from it
- [ ] In a second window, do the same thing for MapXEdges.csv
- [ ] create Java classes that simplify the operations on a record and on a record’s field
- [ ] Permit the user to load or save node and edge csv files
- [ ] In another window, demonstrate a simple A* pathfinding program with either the simple map that you created in Project B or the campus floor map that you created
- [ ] Generate a JAR file

**Comment by Kohmei358** [comment] 2021-02-13 08:44
Duplicate of #70

**Closed by Kohmei358** 2021-02-13 08:44 UTC
Labels: full team
